### ISSUE TITLE
kotlin.UninitializedPropertyAccessException

### ISSUE THREAD

**Issue by aflopezbec** [marusamirox/flutter_facebook_pro#4]
When i call some event in the logs have this error

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.3, on macOS 13.0.1 22A400 darwin-arm, locale es-419)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.72.0)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

```Failed to handle method call
E/MethodChannel#flutter_facebook_sdk/methodChannel( 3603): kotlin.UninitializedPropertyAccessException: lateinit property logger has not been initialized
E/MethodChannel#flutter_facebook_sdk/methodChannel( 3603): 	at app.dev.flutter_facebook_pro.FlutterFacebookSdkPlugin.logEvent(FlutterFacebookSdkPlugin.kt:174)
E/MethodChannel#flutter_facebook_sdk/methodChannel( 3603): 	at app.dev.flutter_facebook_pro.FlutterFacebookSdkPlugin.onMethodCall(FlutterFacebookSdkPlugin.kt:92)
E/MethodChannel#flutter_facebook_sdk/methodChannel( 3603): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#flutter_facebook_sdk/methodChannel( 3603): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#flutter_facebook_sdk/methodChannel( 3603): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#flutter_facebook_sdk/methodChannel( 3603): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#flutter_facebook_sdk/methodChannel( 3603): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#flutter_facebook_sdk/methodChannel( 3603): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter_facebook_sdk/methodChannel( 3603): 	at android.os.Looper.loop(Looper.java:223)
E/MethodChannel#flutter_facebook_sdk/methodChannel( 3603): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/MethodChannel#flutter_facebook_sdk/methodChannel( 3603): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_facebook_sdk/methodChannel( 3603): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/MethodChannel#flutter_facebook_sdk/methodChannel( 3603): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) ```

**Comment by PashaArkus** [comment]
I have the same problem
